repos:
-   repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
    - id: black
      language_version: python
      args:
        - --line-length=88
        - --target-version=py38

-   repo: https://github.com/myint/autoflake
    rev: v2.0.2
    hooks:
    -   id: autoflake
        args:
        - --recursive
        - --in-place
        - --remove-all-unused-imports
        - --remove-unused-variables
        - --expand-star-imports
        - --exclude
        - __init__.py
        - --remove-duplicate-keys
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
-   repo: https://github.com/timothycrosley/isort
    rev: 5.12.0  # pick the isort version you'd like to use from https://github.com/timothycrosley/isort/releases
    hooks:
    -   id: isort
        args:
        - --profile
        - black
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
    -   id: check-yaml
        args:
        -   --unsafe
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
    -   id: pyupgrade
        args:
        - --py3-plus
        - --keep-runtime-typing
-   repo: https://github.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args:
        - --max-line-length=88
        - --extend-ignore=E203
        - --ignore=D100,D101,D102,D103,D104,D105,D106,D107,D202,D204,D205,D400,D401,D403,D413,DAR101,DAR, N815, F811,B008, W503, E712
